// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdevAPI.Data;

#nullable disable

namespace OdevAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OdevAPI.Entities.AuditLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<DateTimeOffset>("ChangedAt")
                    .HasColumnType("TEXT");
                b.Property<string>("ChangedBy")
                    .HasColumnType("TEXT");
                b.Property<string>("EntityId")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("NewValues")
                    .HasColumnType("TEXT");
                b.Property<string>("OldValues")
                    .HasColumnType("TEXT");
                b.Property<string>("TableName")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("OdevAPI.Entities.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<int>("AvailableCopies")
                    .HasColumnType("INTEGER");
                b.Property<int>("CategoryId")
                    .HasColumnType("INTEGER");
                b.Property<string>("Description")
                    .HasColumnType("TEXT");
                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<int>("TotalCopies")
                    .HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("CategoryId");
                b.ToTable("Books");
            });

            modelBuilder.Entity("OdevAPI.Entities.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Description")
                    .HasColumnType("TEXT");
                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Categories");
            });

            modelBuilder.Entity("OdevAPI.Entities.Loan", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<int>("BookId")
                    .HasColumnType("INTEGER");
                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("TEXT");
                b.Property<DateTimeOffset>("DueDate")
                    .HasColumnType("TEXT");
                b.Property<DateTimeOffset>("LoanDate")
                    .HasColumnType("TEXT");
                b.Property<string>("Notes")
                    .HasColumnType("TEXT");
                b.Property<DateTimeOffset?>("ReturnDate")
                    .HasColumnType("TEXT");
                b.Property<int>("Status")
                    .HasColumnType("INTEGER");
                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");
                b.Property<int>("UserId")
                    .HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("BookId");
                b.HasIndex("UserId");
                b.ToTable("Loans");
            });

            modelBuilder.Entity("OdevAPI.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Phone")
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Users");
            });

            modelBuilder.Entity("OdevAPI.Entities.Book", b =>
            {
                b.HasOne("OdevAPI.Entities.Category", null)
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("OdevAPI.Entities.Loan", b =>
            {
                b.HasOne("OdevAPI.Entities.Book", null)
                    .WithMany()
                    .HasForeignKey("BookId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("OdevAPI.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
